/**
 * The aurora field: the shell's own background, and elevation level e0.
 *
 * Four layers, described in `src/styles/field.css`. Everything here is markup - the colours are
 * `--aurora-*` tokens so a theme restyles the field, and the same tokens are what the blur
 * snapshot paints from, so the cheap fallback and the real field cannot drift apart.
 *
 * This is the correct default. It is a handful of gradients and one noise tile, it costs
 * essentially nothing, and it is what the design draws. The WebGL shaders are still there for a
 * theme or a user who asks for one by name (`{ kind: 'shader' }`), and render over the top.
 */

/** Ties the grain rect to its filter without colliding if the field is ever mounted twice. */
const GRAIN_FILTER_ID = 'aura-field-grain-filter';

export function AuroraField(): React.JSX.Element {
  return (
    <div className="aura-field" data-testid="aurora-field">
      <div className="aura-field-layer aura-field-primary" />
      <div className="aura-field-layer aura-field-secondary" />
      <div className="aura-field-layer aura-field-vignette" />

      {/*
        Fractal noise, generated by the browser rather than shipped as an image: it is a few
        hundred bytes of markup instead of a texture, it is resolution-independent, and it needs
        no `img-src data:` in the CSP.

        `pointer-events: none` is not cosmetic. This element covers the entire screen, so without
        it every click on the desktop would land here and the shell would be inert.
      */}
      <svg
        className="aura-field-layer aura-field-grain"
        aria-hidden="true"
        focusable="false"
        preserveAspectRatio="none"
      >
        <filter id={GRAIN_FILTER_ID}>
          <feTurbulence type="fractalNoise" baseFrequency="0.8" numOctaves={3} stitchTiles="stitch" />
          {/* Turbulence is coloured; the field wants luminance noise, not confetti. */}
          <feColorMatrix type="saturate" values="0" />
        </filter>
        <rect width="100%" height="100%" filter={`url(#${GRAIN_FILTER_ID})`} />
      </svg>
    </div>
  );
}
